name: Deploy to production

on:
  workflow_dispatch:

jobs:
  deploy-dashboard:
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/template-deploy.yml
    with:
      vercel_org_id: team_C4VZgUPr0FlKic3I11Ygmgkt
      vercel_project_id: prj_inISPOA4LaYaEJH45Q8DZ32FxJHw
      project_name: dashboard
      environment: production
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}